project: 
  type: website
  output-dir: docs

  
website: 
  title:  <img src = "static/img/unicef2.png" alt = "Unicef" width = "175" height = "43.75" img>
  favicon: /static/img/who-emblem.png
  site-url: https://benguimbis.github.io/registration_website/
  cookie-consent: true
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Attention** - La période d'enregistrement est prolongée au  **31 août 2024**"
    type: warning
    position: above-navbar
  repo-url: https://github.com/benguimbis/registration_website
  repo-actions: [source, issue]
  
  navbar: 
    logo: /static/img/logo-en.svg
    background: light
    foreground: dark
    right: 
      - text: "Accueil"
        href: index.qmd
        icon: bi-house-door-fill
      - text: Enregistrements
        icon: input-cursor-text
        menu: 
          - text: 'Enregistrements à la réunion'
            href: epi/enregistrement.qmd
          - text: 'Enregistrements journée 1'
            href: epi/jour1.qmd
          - text: 'Enregistrements journée 2'
            href: epi/jour2.qmd            
          - text: 'Enregistrements journée 3'
            href: epi/jour3.qmd
          - text: 'Enregistrements journée 4'
            href: epi/jour4.qmd            
      - text: Agenda
        icon: calendar-date-fill
        menu: 
          - text: "Agenda et Présentations"
            href: epi/agenda.qmd
          - text: "Jour 1"
            href: epi/day1.qmd
          - text: "jour 2"
            href: epi/day2.qmd
          - text: "Jour 3"
            href: epi/day3.qmd
          - text: "Jour 4"
            href: epi/day4.qmd
      - text: Note d'information
        href: epi/note.qmd
        icon: bi-airplane-fill
      - text: "Contact"
        file:  epi/about.qmd
        icon: bi-person-lines-fill
   
  
  page-footer:
    left: |
      {{< fa regular copyright >}} WHO-IST CA 2024<br>      
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org)
    right:
      - text: <img src = "static/img/logo-en.svg"  alt = "WHO-AFRO" width = "250" height = "62.5">&nbsp;
        href: https://www.afro.who.int/
        aria-label: WHO-AFRO
      - text: <img src = "static/img/unicef2.png" alt = "Unicef" width = "150" height = "37.5" img>
        href: https://www.unicef.org/wca/
        aria-label: Unicef-WCA





format: 
  html: 
    theme: dinty.scss
    css: styles.css
    highlight-style: kate
    code-block-bg: true
    code-block-border-left: "#78c2ad"
    code-fold: true
    code-tools: false
    fig-width: 9
    fig-height: 6
    fig-align: center
    other-links: 
      - text: "Telecharger Agenda"
        icon: download
        href: meeting.ics

execute:
  freeze: auto

lang: fr

language: 
  fr:
    title-block-published: "Mis à jour"
  