project: 
  type: website
  output-dir: docs

  
website: 
  title: Revue annuelle du Programme Élargie de Vaccination de la République Démocratique du Congo, Matadi 2025
  favicon: /static/img/fav.png
  site-url: https://who-ist-ca.github.io/Reunion-Annuelle-PEV/
  cookie-consent: true
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Attention** - Cette information est importante"
    type: warning
    position: above-navbar

  
  navbar: 
    title: false
    logo: /static/img/header.png
    background: light
    foreground: dark
    right: 
      - text: "Accueil"
        href: index.qmd
        icon: bi-house-door-fill
      - text: Enregistrements
        icon: input-cursor-text
        menu: 
          - text: 'Enregistrements à la réunion'
            href: epi/enregistrement.qmd
          - text: 'Enregistrements journée 1'
            href: epi/jour1.qmd
          - text: 'Enregistrements journée 2'
            href: epi/jour2.qmd            
          - text: 'Enregistrements journée 3'
            href: epi/jour3.qmd
          - text: 'Enregistrements journée 4'
            href: epi/jour4.qmd            
          - text: 'Enregistrements journée 5'
            href: epi/jour5.qmd            

      - text: Agenda et Présentations
        icon: calendar-date-fill
        menu: 
          - text: "Agenda"
            href: epi/agenda.qmd
          - text: "Jour 1"
            href: epi/day1.qmd
          - text: "jour 2"
            href: epi/day2.qmd
          - text: "Jour 3"
            href: epi/day3.qmd
          - text: "Jour 4"
            href: epi/day4.qmd
      - text: Note d'information
        href: epi/note.qmd
        icon: bi-airplane-fill
      - text: "Contact"
        file:  epi/about.qmd
        icon: bi-person-lines-fill
  search:
    location: navbar
    type: overlay
  
  page-footer:
    left: |
      {{< fa regular copyright >}} PEV-RDC 2025<br>      
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org)
    right:
      - text: <img src = "/static/img/footer.png" alt = "Unicef" width = "529px" height = "59px">
        aria-label: PEV-RDC

  back-to-top-navigation: true



format: 
  html: 
    theme: dinty.scss
    css: styles.css
    highlight-style: kate
    code-block-bg: true
    code-block-border-left: "#78c2ad"
    code-fold: true
    code-tools: false
    fig-width: 9
    fig-height: 6
    fig-align: center
    other-links: 
      - text: "Telecharger Agenda"
        icon: download
        href: meeting.ics

execute:
  freeze: auto

lang: fr

language: 
  fr:
    title-block-published: "Mis à jour"
  