---
title: Révue annuelle du Programme Élargi de Vaccination de la République Démocratique du Congo
subtitle: <i class="fa-solid fa-hotel"></i>  Matadi-RDC<br/><i class="fa-solid fa-calendar"></i>  Du 15 au 21 décembre 2025
listing:
  feed: true
  contents: epi
  sort: "date desc" 
  type: grid
  grid-columns: 4
  image-height: 250px
  page-size: 100
  categories: false
page-layout: full
title-block-banner: true
code-tools: false
---

## Message de Bienvenue du Directeur du PEV



Chers acteurs du Programme Elargi de Vaccination (PEV) aux différents niveaux de notre système de santé,

Je vous souhaite la bienvenue à la revue annuelle du PEV 2025 qui se tiendra du 15 au 21 décembre 2025, dans la ville portuaire de Matadi.
Vous avez, tous, chacun à son niveau, donné le meilleur de vous-même pour la mise en œuvre du Plan d’Action Opérationnel (PAO) du PEV 2025. Nous avons certes commencé sa mise en œuvre en retard, pour diverses raisons, mais nous avons ensemble rattrapé la mise en œuvre de la plupart des activités. <br>

Cette réunion va nous donner à tous, l’opportunité d’analyser les progrès que nous avons réalisé, ce que nous avons bien fait, ce que nous n’avons pas fait et devrions améliorer. Ce sera aussi l’occasion d’élaborer notre PAO 2026. Notre objectif restera le même : faire de sorte que tous les enfants de notre pays aient accès aux vaccins de notre calendrier auxquels ils ont droit ; que notre système soit en mesure de détecter à temps et répondre rapidement aux épidémies de maladies à prévention vaccinale.
Je compte sur chacun d’entre vous pour faire de cette revue un succès.<br>

**Dr Audry Mulumba**


<br> <br>



**Liens Rapides:** &nbsp;&nbsp;&nbsp;[Enregistrements](epi/enregistrement.qmd){.btn .btn-outline-primary .button-styling .btn role="button" data-toggle="tooltip" title="Je' m'enregistre"}













