---
title: "Agenda"
description: "<strong>Agenda des quatre jours de reunion</strong>"
format: html
#  html:
#    other-links: 
#      - text: "Présentations jour 1"
#        href: day1.html
#      - text: "Présentations jour 2"
#        href: day2.html
#      - text: "Présentations jour 3"
#        href: day3.html
#      - text: "Présentations jour 4"
#        href: day4.html
#image: /static/img/business-time-solid.svg
title-block-banner: false
execute: 
  echo: false
---

| **Horaire** 	| **Activité** 	| **Présentateur/ Modérateur** 	|
|---	|---	|---	|
| **Journée du 09 septembre   2024<br><br>Modérateur de la   journée : TBC** 	|  	|  	|
| 8 :00-8 :30 	| Accueil et enregistrement des     participants 	| Secrétariat 	|
| 8 :30-8 :40 	| Briefing administratif 	| OMS RDC 	|
| 8 :40-8 :50 	| Briefing de sécurité 	| OMS RDC 	|
| 8 :50-9 :00 	| Briefing sur la Prévention du     harcèlement, de l'exploitation et des abus sexuels (PHEAS) 	| OMS RDC 	|
| 9 :00 -10 :00 	| Cérémonie d’ouverture <br> Allocution du Représentant de   l’OMS-RDC   (au nom du Système des   Nations Unies)<br>Allocution de     Gavi<br>Allocution d’ouverture du Ministre en charge de la santé   de la   RDC<br> 	| Ministère de la santé RDC 	|
| 10 :00-10 :30 	| Pause-café 	|  	|
| 10 :30-11 :00 	| Présentation des délégations   pays   et recueil des attentes 	| Franck Mboussou (Point Focal OMS IST-CA) 	|
| **Session introductive : Situation de   la   vaccination, de la surveillance   des maladies à prévention vaccinale et     paysage de financement<br> <br>Modérateur : Dr Roch   Placide Bissengue (Directeur du PEV RCA)** 	|  	|  	|
| 11 :00-11 :20 	| Point sur le suivi des     recommandations de la réunion des Directeurs de PEV d’Afrique centrale   de   2023 	| Shalom Tchokfe Ndoula (SP du PEV Cameroun) 	|
| 11 :20-13 :00 	| Revue des stands pays avec des     Posters résumant la situation de la vaccination et de la surveillance   des   maladies à prévention vaccinale. 	| Délégations des 10 pays, <br>WHO IST CA<br>UNICEF WCARO 	|
| 13 :00 – 14 :00 	| Pause-déjeuner 	|  	|
| 14 :00-14 :20 	| GAVI 6.0 : ce qu’il faut   savoir 	| GAVI 	|
| 14 :20-14 :40 	| Considérations pour la   transition   et intégration des campagnes de santé vers/avec les soins de santé   primaires. 	| OMS HQ 	|
| 14 :40-15 :00 	| Leçons apprises des premières     introductions des vaccins antipaludiques en Afrique 	| Adidja Amani (AMVIRA Incident Manager) 	|
| 15 :00 -15 :20 	| Discussions 	| Modérateur 	|
| 15 :20-15 :30 	| Orientations sur le   déroulement   des panels de partage d’expérience 	| Audry Mulumba (Directeur PEV RDC) 	|
| **Session 2: Panels d'échange   d'expérience** 	|  	|  	|
| **Panel 1 : Big   catch-up** 	|  	|  	|
| 15 :30-15 :50 	| Situation des enfants   zéro-doses   et de la préparation & mise en œuvre des plans rattrapage en   Afrique centrale 	| Franck Mboussou & Yolande Vuo-Masembe (OMS IST-CA ) 	|
| 15 : 50-16 :10 	| Vaccins pour le Big Catch-up:     situation des commandes pour les pays d’Afrique centrale et   orientations pour   la gestion 	| UNICEF WCARO 	|
| 16:10-16:30 	| Suivi et reporting du   rattrapage   en matière de vaccination essentielle dans le contexte du Big   Catch Up 	| Carolina Danovaro (OMS/HQ) 	|
| 16:30-17:00 	| Pause-café 	|  	|
| 17 :00 -18 :00 	| Présentation des panelistes des   pays   : Cameroun, RDC, Angola et Tchad 	|  	|
| 18:00-18:20 	| Discussions 	|  	|
| **Journée du 10   septembre 2024<br>   <br>Modérateur de la journée : TBC** 	|  	|  	|
| 8 :30 -8 :45 	| Synthèse de la première   journée 	|  	|
| **Panel     2 : Introduction des nouveaux vaccins<br><br>Modérateur :   Audry Mulumba (Directeur du PEV RDC)** 	|  	|  	|
| 8 :45 –9:05 	| Mises à jour sur les nouveaux     vaccins : hexavalent, DTP Boosters, HPV, Malaria, etc. 	| OMS/HQ 	|
| 9 :05 –9:25 	| Introduction du Vaccin contre le HPV : évolution des couvertures   vaccinales et guide OMS sur le vaccin anti-HPV dose unique. 	| Paul Bloem (OMS HQ) 	|
| 9 :25 -10 :15 	| Présentation des panelistes des pays sur les leçons apprises de la   préparation, mise en œuvre, génération de la demande et évaluation   post-introduction, dans le cadre de récentes introduction de nouveaux vaccins   ou vaccins sous-utilisés : Cameroun (HBV chez les garçons, intégration   routine-écoles), Burundi (HepB0 ), Congo (Rota), Gabon ( Fièvre Jaune). 	|  	|
| 10 :15-10 :30 	| Discussion 	|  	|
| 10 :30 -11 :00 	| Pause-café 	|  	|
| **Panel     3 : Engagement politique et financement durable de la   vaccination<br><br>Modérateur     : Directeur du PEV Burundi** 	|  	|  	|
| 11 :00-11 :15 	| Statut de la mise en œuvre de     l’engagement de ADI N°2 :    Augmenter et   assurer la   durabilité des investissement domestiques et allocations   budgétaires sur la vaccination en Afrique. 	| Franck Mboussou (IST-CA/Amos Petus (OMS AFRO) 	|
| 11:15 -12:00 	| Présentation des panelistes des pays : RDC (Plan Mashako et Déclaration   de Kinshasa), Angola (Financement durable de la vaccination), Guinée   Equatoriale (Gestion des financements publiques sur la vaccination par les   partenaires internationaux comme OMS) 	|  	|
| 12 :00-13 :00 	| Discussions 	|  	|
| 13 :00 -14 :00 	| Pause-Déjeuner 	|  	|
| **Panel     4 : Vaccination et santé digitale<br>Modérateur :  Directeur du PEV Tchad** 	|  	|  	|
| 14 :00 -14 :15 	| Expérience de l’Amérique du   Sud   dans le déploiement des REV et recommandations pour la région africaine 	| Carolina Danovaro, OMS HQ 	|
| 14 :15 – 14 :30 	| SMART Guidelines et   application   dans la surveillance des MPV 	| Patricia Ndumbi, Digital Health, OMS HQ 	|
| 14:30-14:45 	| Utilisation de GIS dans     l’identification des zones à risque d’enfants zéro-dose 	| Roland Ngom, PPHM, OMS AFRO 	|
| 14:45-15:30 	| Présentation des panelistes sur la digitalisation dans les programmes de   vaccination : Cameroun (planification et enregistrement des données par   session de vaccination), RDC (expérimentation du registre électronique),   Burundi (gestion de la campagne de vaccination contre la Rougeole) 	|  	|
| 15 :30- 16 :00 	| Discussion 	|  	|
| 16 :00-16 :30 	| Pause-café 	|  	|
| 16 :30 – 18 : 00 	| Stratégie EYE et contrôle de fièvre jaune : Protection des travailleurs à haut risque 	| Blaise BATHONDOLIP<br> Marie Eve RAGUENAUD  	|
| **Journée   du 11 Septembre 2024 Modérateur : TBC** 	|  	|  	|
| 8 :30 -8 :45 	| Synthèse de la deuxième   journée 	|  	|
| **Panel 5 VPD et Genre <br>   Modérateur: Jonas Ebina (Directeur du PEV Congo)** 	|  	|  	|
| 8 :45-9 :00 	| Orientations globales sur VPD   et   Genre 	| Carole Tevi Benissan(OMS HQ) 	|
| 9 :00 – 10 :00 	| Présentation des panélistes   des   pays sur la prise en compte de la dimension genre dans les programmes   VPD   : STP, RDC et RCA. 	|  	|
| 10 :00 -10 :30 	| Discussions 	|  	|
| 10 :30-11 :00 	| Pause-café 	|  	|
| **Panel 6 : Surveillance de la   Rougeole** 	|  	|  	|
| 11 :00-11 :15 	| Etat des lieux de la situation   de   la rougeole en Afrique centrale 	| Sylvestre Dongmo (OMS IST-CA)<br>Alice Wimmer (WHO HQ 	|
| 11 :15-12 :15 	| Présentation des panélistes   des   pays sur la détection et réponse aux épidémies de rougeole : RDC,   Cameroun, Guinée Equatoriale, Gabon,   Burundi. 	|  	|
| 12 :15-13 :00 	| Discussions 	|  	|
| 13 :00 -14 :00 	| Pause-déjeuner 	|  	|
| **Session 3: Travaux   de groupes sur les points d’action de la   réunion<br>Modérateur : TBC** 	|  	|  	|
| 14 :00 -14 :10 	| Orientations sur les travaux   de   groupe 	| Christian Akani (OMS IST- CA) 	|
| 14 :10-15 :10 	| Travaux de groupes sur les   points   d’action au terme de la réunion des Directeurs de PEV 2024. 	|  	|
| 15 :10-16 :10 	| Restitution des travaux de   groupe 	|  	|
| 16 :10-16 :40 	| Pause-café 	|  	|
| **Session 4: Eradication et Transition   Polio et Monkeypox<br>Modérateur : TBC** 	|  	|  	|
| 16 :40-17 :10 	| Progrès réalisés dans     l’éradication et transition polio en Afrique centrale. 	| Aissata Diaha 	|
| 17 :10 :17 :30 	| Situation de l’épidémie de     Monkepox et réponse vaccinale en RDC 	| Directeur PEV RDC 	|
| 17 :30- 18 :00 	| Discussions et clôture de la     journée 	|  	|
| **Journée du 12   Septembre 2024** 	|  	|  	|
| **Session 6: Vaccination contre Ebola** 	|  	|  	|
| 8 :30 :9 :30 	| Introduction sur les     Recommandations du SAGE sur les vaccins contre Ebola 	| OMS 	|
| 9 :30-10 :00 	| Expérience de la vaccination     contre Ebola sur le terrain 	| OMS 	|
| 10 :00 -10 :30 	| Pause-café 	|  	|
| 10 :30 -11 :00 	| Pourquoi considérer la     vaccination à but préventif ? 	| OMS 	|
| 11 :00-11 :30 	| Accès aux vaccins contre Ebola   et   application à ICG 	| OMS 	|
| 11 :30 – 12 :30 	| Travaux de groupe sur les     applications ICG + Restitution 	| OMS/Gavi 	|
| 12 :30-13 :00 	| Applications à Gavi sur la     vaccination contre Ebola 	| Gavi 	|
| 13 :00 -14 :00 	| Pause-déjeuner 	|  	|
| 14 :00 -14 :30 	| Engagement communautaire dans   la   vaccination contre Ebola 	| UNICEF 	|
| 14 :30-15 :00 	| Orientations et appuis   techniques   : considérations pratiques pour la vaccination contre Ebola 	| OMS 	|
| 15 :00 -15 :20 	| Expérience de la RDC dans la     vaccination contre Ebola 	| PEV RDC 	|
| 15 :20-15 :40 	| Pause-café 	|  	|
| 15 :40-16 :00 	| Evaluation de la réunion par   les   participants 	|  	|
| 16 :00-16 :30 	| Cérémonie de     cloture<br>Allocution du Représentant de l’UNICEF-RDC (au nom   du   Système des Nations   Unies)<br>Allocution de Gavi<br>Allocution   de clôture du Ministre en charge de la   santé de la RDC 	|  	|
| 15 :00 -15 :20 	| Expérience de la RDC dans la   vaccination contre Ebola 	| PEV RDC 	|
| 15 :20-15 :40 	| Pause-café 	|   	|
| 15 :40-16 :00 	| Evaluation de la réunion par   les participants 	|   	|
| 16 :00-16 :30 	| Cérémonie de   cloture<br/>Allocution du Représentant de l’UNICEF-RDC (au nom du   Système des Nations Unies)<br/>Allocution de Gavi<br/>Allocution   de clôture du Ministre en charge de la santé de la RDC 	|   	|