---
title: "Inscriptions"
description: "<strong>Inscriptions pour la reunion</strong>"
#image: /static/img/pen-nib-solid.svg
title-block-banner: false
execute: 
  echo: false
---


Chers participants et modérateurs,

Nous sommes ravis de vous accueillir à Matadi! Pour garantir une expérience fluide, veuillez vous enregistrer en suivant les étapes ci-dessous :

- **Remplissez le formulaire** :
Entrez vos coordonnées (nom, prénom, adresse e-mail, etc.).
- **Validez votre inscription** :
Cliquez sur le bouton **“Enregistrer l'inscription”** pour confirmer votre participation.
- **Téléchargez le calendrier**:
Accedez a la section *Other Links* et cliquez sur **Télécharger Agenda** (à droite de votre écran), puis suivez les instructions d’installation pour ajouter le calendrier à votre application de gestion de calendrier préférée (par exemple, Outlook, Google Calendar, etc.).
N’hésitez pas à nous contacter si vous avez des questions ou des préoccupations. Nous avons hâte de vous retrouver lors de notre événement !

 &nbsp;&nbsp;&nbsp; <div>

```{=html}
<embed width="800px" height="950px" src="https://worldhealthorg.shinyapps.io/inscriptions_revue_rdc/" frameborder="0" marginwidth="0" marginheight="0" style="border:none; max-width:100%; max-height:100%; color: #ffffff" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </embed>

```

</div>


