---
title: ""
description: "<strong>Informations complémentaires et indications pratiques</strong>"
#image: /static/img/circle-info-solid.svg
format: 
  html: 
    toc: true
    toc-title: "Aller à"
title-block-banner: false
date-modified: last-modified
execute: 
  echo: false
---



## Note d'information

### Dates et lieu 

La réunion se tiendra du **15 au 21 décembre 2025** à l’hôtel *Leydia* de la ville de Matadi<br/>
Email: [suivievaluationpev@gmail.com](mailto:suivievaluationpev@gmail.com)-Téléphone : +243 89 763 44 12 / +243 81 488 58 05

### Perdiem

Les participants recevront un perdiem conforme au taux GIBS applicable. Les pauses café de groupe seront servies durant l’atelier et offert payés par l’organisation. Tout autre repas sera pris en charge par chaque participant.
Il est vivement recommandé à tous les participants pris en charge par l'organisation de se faire payer le perdiem dans leur lieu de résidence avant d’effectuer le voyage.


### Monnaie

La monnaie officielle de la RDC est le Franc Congolais (FC). Le taux de change : 1 USD = 2300 FC (Decembre 2025). La devise américaine (USD) est acceptée dans tous les commerces de Matadi.

### Accueil à Matadi

Pour les agents du MSHPH, l'organisation mettra à leur disposition  un moyen de transport pour le trajet Kinshasa-Matadi-Kinshasa. Par ailleurs, l'organisation couvrira les frais de transport pour les trajets entre les provinces et Kinshasa. 

Les participants sont responsables de leur déplacement dans la ville de Matadi. Aucune disposition particulière ne sera mise en place pour leur réception à Matadi. Toutefois, nous encourageons les participants à contacter la cellule de suivi et evaluation du PEV  [suivievaluationpev@gmail.com](mailto:suivievaluationpev@gmail.com) pour plus amples informations.

### Prévention des Méconduites Sexuelles 

Un briefing sur la prévention des méconduites sexuelles sera dispensé aux membres de la mission à leur arrivée (généralement en synchronisation avec le briefing de sécurité). 

### Securité

La situation sécuritaire à Matadi est relativement calme. Les menaces liées à la sécurité auxquelles les personnes peuvent être confrontées à Matadi sont principalement de la criminalité et des troubles civils. La criminalité est répandue à Matadi, y compris dans la commune de XXXXXXX. Les activités criminelles comprennent le vol à la tire, le pickpocket, les cambriolages, les braquages d’individus et de véhicules. Les criminels concentrent leurs attaques sur les personnes perçues comme ayant de l'argent ou des objets de valeur. Les acteurs criminels identifiés sont les enfants de la rue communément appelés « Shegués », les gangs organisés « Kulunas ».
Il est conseillé d'éviter les grands rassemblements publics, en particulier les manifestations politiques.
Il est également important d'être conscient du danger que peut représenter la circulation routière à Matadi. Les accidents de la route sont très fréquents à Kinshasa où le code de la route est très peu respecté par les usagers. 

Il est recommandé de respecter les précautions de sécurité habituelles et de contacter le responsable de la sécurité et son assistant aux coordonnées ci-après :

XXXXXXXXXX 
XXXXXXXXXXX

### Hébergement

Tous les participants ont un libre choix de leurs hotels. Toutefois, nous les encourageons à loger aux environ de l'hotel Leydia.





### Climat 

La RDC, a une superficie de 2 345 000 Km2 et une population estimée à 102 millions d’habitants, elle constitue un patrimoine culturel exceptionnel avec près de 450 ethnies. La diversité culturelle, artistique et linguistique constitue l’une des grandes richesses de la RDC. 
La ville de Matadi connaît deux saisons réparties comme suit : la saison sèche, de mai à septembre et la saison des pluies, d’octobre à avril. Pendant le mois de décembre qui correspond à la saison des pluies, il y a d’intense soleil, les températures oscillent entre 30°C et 35°C.

### Langues 

Le français est la langue administrative officielle, le lingala et le kikongo sont les principales langues locales parlées à Matadi.



### Appels Telephoniques Internationaux/ Acces Internet 

Des installations pour les appels téléphoniques internationaux et l’accès à internet sont disponibles à l’Hôtel Leydia. Les cartes téléphoniques et cartes SIM locales sont vendues  dans les magasins de la ville.

### Heure Locale

Heure de Kinshasa et Brazzaville GMT+1


### Électricité

Le courant électrique en RDC varie entre 3,22 et 4,89 kWh/m2/j. Les prises recommandées sont deux broches rondes.


### Adresse et Contactcs Utiles 

- Direction PEV: [directionpevrdc@gmail.com](mailto:directionpevrdc@gmail.com)
- Suivi et Évaluation PEV:  [suivievaluationpev@gmail.com](mailto:suivievaluationpev@gmail.com)
- Chef de division provinciale du Congo central: +243 85 612 96 60
- Médécin chef d'antenne Matadi: +243 89 86 15 181 
- Chef de Bureau OMS Matadi: +243 81 89 98 506
- Chargé des services généraux: +243 818 153 075

<!-- - Unicef: [amudipanu@unicef.org](amudipanu@unicef.org)- Tel: +243 81 45 87 908]: -->




